custom-commands:
  - name: sprint-add
    help: add issue to active sprint for project
    args:
      - name: ISSUE
        required: true
    script: |
      board_id=466
      active_sprint=$({{jira}} req "/rest/agile/1.0/board/$board_id/sprint?state=active" | jq '.values | .[] | select(.originBoardId | contains($board_id))')
      sprint_id=`echo $active_sprint | jq '.id'`
      sprint_name=`echo $active_sprint | jq '.name'`
      {{jira}} req -Q -M POST "/rest/agile/1.0/sprint/$sprint_id/issue" "{\"issues\":[\"{{args.ISSUE}}\"]}"
      echo "{{args.ISSUE}} added to ${sprint_name}"
endpoint: https://chime.atlassian.net/
